name: Create Archive
on:
  push:
    tags: [ "v*.*.*" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get version name
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'nba-${{ env.RELEASE_VERSION }}.zip'
        exclusions: './screenshots ./.gitignore ./.git ./.github'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "nba-${{ env.RELEASE_VERSION }}.zip"
        token: ${{ secrets.RELEASE_TOKEN }}
        allowUpdates: true
